quarkus:
  banner:
    enabled: true
    path: banner.txt
  http:
    port: 8181
  fx:
    views-root: fxviews
  log:
    console:
      format: '%d{dd-MM-yyyy HH:mm:ss} %-5p [%c] (%t) %s%e%n'
    level: INFO
    category:
      "de.ostfale.qk.ui":
        level: DEBUG
    file:
      enable: true
      path: ${user.home}/.bad_stat/logs/bad-stat.log
      rotation:
        max-backup-index: 5
        max-file-size: 10M
        file-suffix: dd-MM-yyyy

# To start the application using a H2 instance (./mvnw -Dquarkus-profile=prod quarkus:dev)
"%prod":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
        url:  jdbc:h2:file:~/.bad_stat/data/bad-db
      username: sa
      password:
    hibernate-orm:
      database:
        generation: drop-and-create

# To start the application using an H2 (./mvnw -Dquarkus-profile=dev quarkus:dev)
"%dev":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
        url:  jdbc:h2:file:~/.bad_stat/data/bad-db
      username: sa
      password:
    hibernate-orm:
      database:
        generation: drop-and-create
