quarkus:
  banner:
    enabled: true
    path: banner.txt
  http:
    port: 8181
  fx:
    views-root: fxviews
  log:
    console:
      format: '%d{dd-MM-yyyy HH:mm:ss} %-5p [%c] (%t) %s%e%n'
    level: INFO
    category:
      "de.ostfale.qk":
        level: DEBUG
    file:
      enable: true
      path: ${user.home}/.bad_stat/logs/bad-stat.log
      rotation:
        max-backup-index: 5
        max-file-size: 10M
        file-suffix: dd-MM-yyyy

