quarkus:
  banner:
    enabled: true
    path: banner.txt
  http:
    port: 8181
  fx:
    views-root: views

# To start the application using a H2 instance (./mvnw -Dquarkus-profile=prod quarkus:dev)
"%prod":
  quarkus:
    datasource:
      jdbc:
        url:  jdbc:h2:file:~/.bad-stat/data/bad-db
      db-kind: h2
    hibernate-orm:
      database:
        generation: drop-and-create

# To start the application using an H2 (./mvnw -Dquarkus-profile=dev quarkus:dev)
"%dev":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        driver: org.h2.Driver
        url: jdbc:h2:file:d:/db/test;
      username: sa
      password:
    hibernate-orm:
      database:
        generation: drop-and-create
